import { MigrationInterface, QueryRunner } from "typeorm";

export class Uzchess1776168372667 implements MigrationInterface {
    name = 'Uzchess1776168372667'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "souvenirImages" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "souvenirId" integer NOT NULL, "image" character varying(128) NOT NULL, CONSTRAINT "PK_b0f18ebc2d8d8a03a24650a187a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "colors" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "title" character varying(28) NOT NULL, "color" character varying(10) NOT NULL, CONSTRAINT "UQ_e271c8fa9391b29979e3958146e" UNIQUE ("title"), CONSTRAINT "UQ_eb5c5063c1274699dc315aa0766" UNIQUE ("color"), CONSTRAINT "PK_3a62edc12d29307872ab1777ced" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "souvenir_colors" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "souvenirId" integer NOT NULL, "colorId" integer NOT NULL, CONSTRAINT "PK_5c8029ad72955e45daff023102e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course-categories" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "title" character varying(64) NOT NULL, CONSTRAINT "UQ_c89f6e6133185ec599f393e112c" UNIQUE ("title"), CONSTRAINT "PK_ee1da08f0a16f4844011afc6e57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "languages" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "title" character varying(32) NOT NULL, "code" character varying(2) NOT NULL, CONSTRAINT "UQ_06df62e773ec68318919dafacf7" UNIQUE ("title"), CONSTRAINT "UQ_7397752718d1c9eb873722ec9b2" UNIQUE ("code"), CONSTRAINT "PK_b517f827ca496b29f4d549c631d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course-sections" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "courseId" integer NOT NULL, "title" character varying(256) NOT NULL, "order" integer, "date" TIMESTAMP NOT NULL, CONSTRAINT "PK_ff51bed24f139b5295565cfa68f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course-user-lessons" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "courseLessonId" integer NOT NULL, "stoppedAt" integer, "isCompleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_abae7743ff3478049436261f039" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course-lessons" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "courseId" integer NOT NULL, "courseSectionId" integer NOT NULL, "title" character varying(128) NOT NULL, "content" text, "thumbnail" character varying(128) NOT NULL, "video" character varying(256) NOT NULL, "order" integer, "date" TIMESTAMP NOT NULL, "isFree" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_f87f63d5e509215686a97fa75be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course-likes" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "courseId" integer NOT NULL, "date" TIMESTAMP NOT NULL, CONSTRAINT "PK_7142d86d9b2a9c040a5c09f8a40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course-reviews" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "courseId" integer NOT NULL, "rating" integer NOT NULL, "comment" character varying(512), "date" TIMESTAMP NOT NULL, CONSTRAINT "PK_d20a265f1d346b6f8363d0da778" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchased-courses" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "courseId" integer NOT NULL, "isCompleted" boolean NOT NULL DEFAULT false, "date" TIMESTAMP NOT NULL, CONSTRAINT "PK_c7bc0abd074a6c72077fd7c88b1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "difficulties" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "title" character varying(32) NOT NULL, "icon" character varying(128) NOT NULL, CONSTRAINT "UQ_de991ed11f2258b97640f71a45a" UNIQUE ("title"), CONSTRAINT "PK_4c3dd46c9ed9b426d0307e45b3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "courses" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "authorId" integer NOT NULL, "categoryId" integer NOT NULL, "languageId" integer NOT NULL, "difficultyId" integer NOT NULL, "title" character varying(128) NOT NULL, "image" character varying(128) NOT NULL, "price" numeric NOT NULL, "newPrice" numeric, "reviewsCount" integer NOT NULL DEFAULT '0', "rating" numeric, "sectionsCount" integer NOT NULL DEFAULT '0', "lessonsCount" integer NOT NULL DEFAULT '0', "difficultId" integer, CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "authors" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "fullName" character varying(64) NOT NULL, CONSTRAINT "PK_d2ed02fabd9b52847ccb85e6b88" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "book_category" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "title" character varying(64) NOT NULL, CONSTRAINT "UQ_d069f88ba2315c7d7235fd7adea" UNIQUE ("title"), CONSTRAINT "PK_0bfe418ce140d4720d0eede7c3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "book_like" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "bookId" integer NOT NULL, "date" TIMESTAMP NOT NULL, CONSTRAINT "PK_a90c105f80b6a9ea5d7ae493413" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "books" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "authorId" integer NOT NULL, "categoryId" integer NOT NULL, "languageId" integer NOT NULL, "difficultyId" integer NOT NULL, "title" character varying(120) NOT NULL, "image" character varying(128), "description" text NOT NULL, "price" numeric(12,2) NOT NULL, "newPrice" numeric(12,2), "rating" numeric(12,2), "reviewsCount" integer NOT NULL DEFAULT '0', "pages" integer NOT NULL, "pubDate" date NOT NULL, CONSTRAINT "PK_f3f2f25a099d24e12545b70b022" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "book-reviews" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "bookId" integer NOT NULL, "rating" integer NOT NULL, "comment" character varying(512), "date" TIMESTAMP NOT NULL, CONSTRAINT "PK_e89295b13792524340c4ebb69be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."OtpCodes_type_enum" AS ENUM('register', 'passwordReset', 'numberChange')`);
        await queryRunner.query(`CREATE TABLE "OtpCodes" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "code" character varying(6) NOT NULL, "date" TIMESTAMP NOT NULL, "type" "public"."OtpCodes_type_enum" NOT NULL, CONSTRAINT "PK_5492c194bf4ce6d35b13d03dc58" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "souvenirReviews" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "souvenirId" integer NOT NULL, "rating" integer NOT NULL, "comment" character varying(512), CONSTRAINT "PK_0238e964d2dcae5478d9e496007" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cartItems_target_enum" AS ENUM('book', 'souvenir')`);
        await queryRunner.query(`CREATE TABLE "cartItems" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "target" "public"."cartItems_target_enum" NOT NULL, "targetId" integer NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "user_id" integer, CONSTRAINT "PK_bb4f983020f59696f40ea04d6a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "role" character varying NOT NULL DEFAULT 'user', "fullName" character varying(64) NOT NULL, "profileImage" character varying(128), "login" character varying(64) NOT NULL, "loginType" character varying NOT NULL, "password" character varying(128), "birthDate" date, "isVerified" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_2d443082eccd5198f95f2a36e2c" UNIQUE ("login"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "souvenirLikes" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "souvenirId" integer NOT NULL, CONSTRAINT "PK_3d3f43cbb5c64ec419947624bad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "souvenirs" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "title" character varying(128) NOT NULL, "description" text NOT NULL, "price" numeric(12,2) NOT NULL, CONSTRAINT "PK_48244e3bc881a2aedb21d225d23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "report-categories" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "title" character varying(64) NOT NULL, "order" integer, CONSTRAINT "UQ_b86cc835054a2af33ee3185fe94" UNIQUE ("title"), CONSTRAINT "PK_99671371c3eed3572b46aae59b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reports_target_enum" AS ENUM('book', 'course')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "reportCategoryId" integer NOT NULL, "target" "public"."reports_target_enum" NOT NULL, "targetId" integer NOT NULL, "description" character varying(256), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "news" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "title" character varying(256) NOT NULL, "date" TIMESTAMP NOT NULL, "image" character varying(128) NOT NULL, "content" text NOT NULL, CONSTRAINT "PK_39a43dfcb6007180f04aff2357e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "news-views" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "userId" integer NOT NULL, "newsId" integer NOT NULL, "firstDate" TIMESTAMP NOT NULL, "lastDate" TIMESTAMP NOT NULL, "count" integer NOT NULL DEFAULT '1', CONSTRAINT "PK_7d352d0441ac16f45de7472d129" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "terms" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "content" text NOT NULL, CONSTRAINT "PK_33b6fe77d6ace7ff43cc8a65958" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."matches_type_enum" AS ENUM('classic', 'rapid', 'blitz')`);
        await queryRunner.query(`CREATE TYPE "public"."matches_winner_enum" AS ENUM('first', 'second', 'draw')`);
        await queryRunner.query(`CREATE TABLE "matches" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "firstPlayer" integer NOT NULL, "firstPlayerResult" integer NOT NULL, "secondPlayer" integer NOT NULL, "secondPlayerResult" integer NOT NULL, "type" "public"."matches_type_enum" NOT NULL, "moves" integer NOT NULL, "date" TIMESTAMP NOT NULL, "winner" "public"."matches_winner_enum" NOT NULL, CONSTRAINT "PK_8a22c7b2e0828988d51256117f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "players" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "countryId" integer NOT NULL, "fullName" character varying(64) NOT NULL, "image" character varying(128), "classic" integer, "rapid" integer, "blitz" integer, CONSTRAINT "PK_de22b8fdeee0c33ab55ae71da3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "countries" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "title" character varying(64) NOT NULL, "flag" character varying(128) NOT NULL, CONSTRAINT "PK_b2d7006793e8697ab3ae2deff18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'admin', 'superAdmin')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "loginType"`);
        await queryRunner.query(`CREATE TYPE "public"."users_logintype_enum" AS ENUM('phone', 'email')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "loginType" "public"."users_logintype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "souvenirImages" ADD CONSTRAINT "FK_31d21cbd9a593c004d730115c58" FOREIGN KEY ("souvenirId") REFERENCES "souvenirs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "souvenir_colors" ADD CONSTRAINT "FK_6bc5091c613c8c70f79160835f6" FOREIGN KEY ("souvenirId") REFERENCES "souvenirs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "souvenir_colors" ADD CONSTRAINT "FK_22f086bc290b15ff98fcdab6cbb" FOREIGN KEY ("colorId") REFERENCES "colors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course-sections" ADD CONSTRAINT "FK_931c77714b030fd0a6e83053699" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course-user-lessons" ADD CONSTRAINT "FK_157ad5135186a076f395ae7df0b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course-user-lessons" ADD CONSTRAINT "FK_1dc90a4cada70f42c33c49e63d7" FOREIGN KEY ("courseLessonId") REFERENCES "course-lessons"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course-lessons" ADD CONSTRAINT "FK_e90f3ec2176e19819196ea0112b" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course-lessons" ADD CONSTRAINT "FK_f94d260a9779d5992e3f35666f5" FOREIGN KEY ("courseSectionId") REFERENCES "course-sections"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course-likes" ADD CONSTRAINT "FK_087196ee48ba8141274add5867e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course-likes" ADD CONSTRAINT "FK_65f149ea1caf99bf9a0ea7eb8b4" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course-reviews" ADD CONSTRAINT "FK_1f1737a13ea0f2c3b2df9de2acf" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course-reviews" ADD CONSTRAINT "FK_6cb7e5ad5ad436a9bba0830030f" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchased-courses" ADD CONSTRAINT "FK_8bfd092ad8db4b7d23a868a1510" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchased-courses" ADD CONSTRAINT "FK_4386c589f9b3d086cd4d8c9354a" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_fffcbc92f4e8fa650d08be6903d" FOREIGN KEY ("authorId") REFERENCES "authors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_c730473dfb837b3e62057cd9447" FOREIGN KEY ("categoryId") REFERENCES "course-categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_a09de3e6027500ac44609a8055f" FOREIGN KEY ("languageId") REFERENCES "languages"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_a02dde1220ef2a2032d657858c9" FOREIGN KEY ("difficultId") REFERENCES "difficulties"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_like" ADD CONSTRAINT "FK_65ca506d5da2ed4b7487c7131a3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_like" ADD CONSTRAINT "FK_d4ad377aa821dd41906d6884656" FOREIGN KEY ("bookId") REFERENCES "books"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_54f49efe2dd4d2850e736e9ab86" FOREIGN KEY ("authorId") REFERENCES "authors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_a0f13454de3df36e337e01dbd55" FOREIGN KEY ("categoryId") REFERENCES "book_category"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_49060974a6295b7f70ac2c102b5" FOREIGN KEY ("languageId") REFERENCES "languages"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_78f9d0c7bf6c0588b6d06fd1aef" FOREIGN KEY ("difficultyId") REFERENCES "difficulties"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book-reviews" ADD CONSTRAINT "FK_af9f8cd91d0ad204cbc08e3216d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book-reviews" ADD CONSTRAINT "FK_bd6e7af4a5364b12cca255c194a" FOREIGN KEY ("bookId") REFERENCES "books"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "OtpCodes" ADD CONSTRAINT "FK_096421b244d436ed6cc89483937" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "souvenirReviews" ADD CONSTRAINT "FK_926130542dc0e70c6d72d10fcb5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "souvenirReviews" ADD CONSTRAINT "FK_92d8236315742d1976a164ad687" FOREIGN KEY ("souvenirId") REFERENCES "souvenirs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cartItems" ADD CONSTRAINT "FK_0cbe275edf66ddab61e9e3527bd" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "souvenirLikes" ADD CONSTRAINT "FK_67efa4f8ef0a5b7546cad6492ce" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "souvenirLikes" ADD CONSTRAINT "FK_6a13f5356fce137f8a98d69e62b" FOREIGN KEY ("souvenirId") REFERENCES "souvenirs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_c95b2561b3a6f8ab7e4d17af335" FOREIGN KEY ("reportCategoryId") REFERENCES "report-categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_a31729358d7f14c5620af2d90cc" FOREIGN KEY ("firstPlayer") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_d49bc69db1280af5a8f4c41ab72" FOREIGN KEY ("secondPlayer") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "players" ADD CONSTRAINT "FK_7d976e6c0eaf82fee3975d8e98a" FOREIGN KEY ("countryId") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "players" DROP CONSTRAINT "FK_7d976e6c0eaf82fee3975d8e98a"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_d49bc69db1280af5a8f4c41ab72"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_a31729358d7f14c5620af2d90cc"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_c95b2561b3a6f8ab7e4d17af335"`);
        await queryRunner.query(`ALTER TABLE "souvenirLikes" DROP CONSTRAINT "FK_6a13f5356fce137f8a98d69e62b"`);
        await queryRunner.query(`ALTER TABLE "souvenirLikes" DROP CONSTRAINT "FK_67efa4f8ef0a5b7546cad6492ce"`);
        await queryRunner.query(`ALTER TABLE "cartItems" DROP CONSTRAINT "FK_0cbe275edf66ddab61e9e3527bd"`);
        await queryRunner.query(`ALTER TABLE "souvenirReviews" DROP CONSTRAINT "FK_92d8236315742d1976a164ad687"`);
        await queryRunner.query(`ALTER TABLE "souvenirReviews" DROP CONSTRAINT "FK_926130542dc0e70c6d72d10fcb5"`);
        await queryRunner.query(`ALTER TABLE "OtpCodes" DROP CONSTRAINT "FK_096421b244d436ed6cc89483937"`);
        await queryRunner.query(`ALTER TABLE "book-reviews" DROP CONSTRAINT "FK_bd6e7af4a5364b12cca255c194a"`);
        await queryRunner.query(`ALTER TABLE "book-reviews" DROP CONSTRAINT "FK_af9f8cd91d0ad204cbc08e3216d"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_78f9d0c7bf6c0588b6d06fd1aef"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_49060974a6295b7f70ac2c102b5"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_a0f13454de3df36e337e01dbd55"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_54f49efe2dd4d2850e736e9ab86"`);
        await queryRunner.query(`ALTER TABLE "book_like" DROP CONSTRAINT "FK_d4ad377aa821dd41906d6884656"`);
        await queryRunner.query(`ALTER TABLE "book_like" DROP CONSTRAINT "FK_65ca506d5da2ed4b7487c7131a3"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_a02dde1220ef2a2032d657858c9"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_a09de3e6027500ac44609a8055f"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_c730473dfb837b3e62057cd9447"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_fffcbc92f4e8fa650d08be6903d"`);
        await queryRunner.query(`ALTER TABLE "purchased-courses" DROP CONSTRAINT "FK_4386c589f9b3d086cd4d8c9354a"`);
        await queryRunner.query(`ALTER TABLE "purchased-courses" DROP CONSTRAINT "FK_8bfd092ad8db4b7d23a868a1510"`);
        await queryRunner.query(`ALTER TABLE "course-reviews" DROP CONSTRAINT "FK_6cb7e5ad5ad436a9bba0830030f"`);
        await queryRunner.query(`ALTER TABLE "course-reviews" DROP CONSTRAINT "FK_1f1737a13ea0f2c3b2df9de2acf"`);
        await queryRunner.query(`ALTER TABLE "course-likes" DROP CONSTRAINT "FK_65f149ea1caf99bf9a0ea7eb8b4"`);
        await queryRunner.query(`ALTER TABLE "course-likes" DROP CONSTRAINT "FK_087196ee48ba8141274add5867e"`);
        await queryRunner.query(`ALTER TABLE "course-lessons" DROP CONSTRAINT "FK_f94d260a9779d5992e3f35666f5"`);
        await queryRunner.query(`ALTER TABLE "course-lessons" DROP CONSTRAINT "FK_e90f3ec2176e19819196ea0112b"`);
        await queryRunner.query(`ALTER TABLE "course-user-lessons" DROP CONSTRAINT "FK_1dc90a4cada70f42c33c49e63d7"`);
        await queryRunner.query(`ALTER TABLE "course-user-lessons" DROP CONSTRAINT "FK_157ad5135186a076f395ae7df0b"`);
        await queryRunner.query(`ALTER TABLE "course-sections" DROP CONSTRAINT "FK_931c77714b030fd0a6e83053699"`);
        await queryRunner.query(`ALTER TABLE "souvenir_colors" DROP CONSTRAINT "FK_22f086bc290b15ff98fcdab6cbb"`);
        await queryRunner.query(`ALTER TABLE "souvenir_colors" DROP CONSTRAINT "FK_6bc5091c613c8c70f79160835f6"`);
        await queryRunner.query(`ALTER TABLE "souvenirImages" DROP CONSTRAINT "FK_31d21cbd9a593c004d730115c58"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "loginType"`);
        await queryRunner.query(`DROP TYPE "public"."users_logintype_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "loginType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`DROP TABLE "countries"`);
        await queryRunner.query(`DROP TABLE "players"`);
        await queryRunner.query(`DROP TABLE "matches"`);
        await queryRunner.query(`DROP TYPE "public"."matches_winner_enum"`);
        await queryRunner.query(`DROP TYPE "public"."matches_type_enum"`);
        await queryRunner.query(`DROP TABLE "terms"`);
        await queryRunner.query(`DROP TABLE "news-views"`);
        await queryRunner.query(`DROP TABLE "news"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_target_enum"`);
        await queryRunner.query(`DROP TABLE "report-categories"`);
        await queryRunner.query(`DROP TABLE "souvenirs"`);
        await queryRunner.query(`DROP TABLE "souvenirLikes"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "cartItems"`);
        await queryRunner.query(`DROP TYPE "public"."cartItems_target_enum"`);
        await queryRunner.query(`DROP TABLE "souvenirReviews"`);
        await queryRunner.query(`DROP TABLE "OtpCodes"`);
        await queryRunner.query(`DROP TYPE "public"."OtpCodes_type_enum"`);
        await queryRunner.query(`DROP TABLE "book-reviews"`);
        await queryRunner.query(`DROP TABLE "books"`);
        await queryRunner.query(`DROP TABLE "book_like"`);
        await queryRunner.query(`DROP TABLE "book_category"`);
        await queryRunner.query(`DROP TABLE "authors"`);
        await queryRunner.query(`DROP TABLE "courses"`);
        await queryRunner.query(`DROP TABLE "difficulties"`);
        await queryRunner.query(`DROP TABLE "purchased-courses"`);
        await queryRunner.query(`DROP TABLE "course-reviews"`);
        await queryRunner.query(`DROP TABLE "course-likes"`);
        await queryRunner.query(`DROP TABLE "course-lessons"`);
        await queryRunner.query(`DROP TABLE "course-user-lessons"`);
        await queryRunner.query(`DROP TABLE "course-sections"`);
        await queryRunner.query(`DROP TABLE "languages"`);
        await queryRunner.query(`DROP TABLE "course-categories"`);
        await queryRunner.query(`DROP TABLE "souvenir_colors"`);
        await queryRunner.query(`DROP TABLE "colors"`);
        await queryRunner.query(`DROP TABLE "souvenirImages"`);
    }

}
